language: rust
sudo: false

rust: stable

matrix:
    include:
        - os: linux
          env: TARGET=i686-unknown-linux-musl

        - os: linux
          env: TARGET=x86_64-unknown-linux-musl

        - os: osx
          env: TARGET=i686-apple-darwin
          
        - os: osx
          env: TARGET=x86_64-apple-darwin

cache: cargo

before_cache:
    # Travis can't cache files that are not readable by "others"
    - chmod -R a+r $HOME/.cargo

branches:
    only:
        - master

# Disable tests for now.
script: cargo build --verbose
