environment:
	global:
		RUST_VERSION: stable

	matrix:
		- TARGET: i686-pc-windows-gnu
		- TARGET: x86_64-pc-windows-gnu
		- TARGET: i686-pc-windows-msvc
		- TARGET: x86_64-pc-windows-msvc

install:
	- ps: >-
			If ($Env:TARGET -eq 'x86_64-pc-windows-gnu') {
				$Env:PATH += ';C:\msys64\mingw64\bin'
			} ElseIf ($Env:TARGET -eq 'i686-pc-windows-gnu') {
				$Env:PATH += ';C:\msys64\mingw32\bin'
			}
	- curl -sSf -o rustup-init.exe https://win.rustup.rs/
	- rustup-init.exe -y --default-host %TARGET% --default-toolchain %RUST_VERSION%
	- set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
	- rustc -Vv
	- cargo -V

# It's a library; we don't need to deploy anything.
deploy: off

# Don't build anything with MSBuild. We use cargo in the install section.
build: false

cache:
	- C:\Users\appveyor\.cargo\registry
	- target

branches:
	only:
		- master


# Build but don't test for now.
test_script:
	- cargo build --verbose
#	- cargo test
